---
on:
  workflow_call:
    inputs:
      add-paths:
        description: "Paths to "
        required: false
        type: string

      org:
        description: "The organisation for this"
        required: false
        default: "SUSE"
        type: string

      image-version:
        description: "The version of the image to use for the workflow"
        required: false
        default: "ubunut-latest"
        type: string

    # secrets:
    #  deploy-key:
    #    description: "The deploy key for successful HTML builds"
    #    required: false
    #    type: string

jobs:
  print-username:
    runs-on: ${{ inputs.image-version }}

    steps:
      - name: Print the input name to STDOUT
        run: echo The image is ${{ inputs.image-version }}
